[package]
name = "sqlite-hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
digest = "0.10.7"
hex = "0.4.3"
md-5 = "0.10.6"
sha2 = "0.10.9"
sqlite-loadable = "0.0.5"
